
///////////////////  CORE_DEFINE /////////////////////////
`define XF100_INSTR_SIZE     32
`define XF100_PC_SIZE        32
`define XF100_RFIDX_WIDTH    5
`define XF100_XLEN           32



///////////////////  DECODE_DEFINE /////////////////////////
`define ALU_INFO_DEF_BASE  0
`define ALU_INFO_DEF_ADD_LSB    `ALU_INFO_DEF_BASE
`define ALU_INFO_DEF_ADD_MSB    `ALU_INFO_DEF_ADD_LSB+1-1
`define ALU_INFO_DEF_ADD        `ALU_INFO_DEF_ADD_MSB:`ALU_INFO_DEF_ADD_LSB
`define ALU_INFO_DEF_SUB_LSB    `ALU_INFO_DEF_ADD_MSB+1
`define ALU_INFO_DEF_SUB_MSB    `ALU_INFO_DEF_SUB_LSB+1-1
`define ALU_INFO_DEF_SUB        `ALU_INFO_DEF_SUB_MSB:`ALU_INFO_DEF_SUB_LSB
`define ALU_INFO_DEF_SLL_LSB    `ALU_INFO_DEF_SUB_MSB+1
`define ALU_INFO_DEF_SLL_MSB    `ALU_INFO_DEF_SLL_LSB+1-1
`define ALU_INFO_DEF_SLL        `ALU_INFO_DEF_SLL_MSB:`ALU_INFO_DEF_SLL_LSB
`define ALU_INFO_DEF_SLT_LSB    `ALU_INFO_DEF_SLL_MSB+1
`define ALU_INFO_DEF_SLT_MSB    `ALU_INFO_DEF_SLT_LSB+1-1
`define ALU_INFO_DEF_SLT        `ALU_INFO_DEF_SLT_MSB:`ALU_INFO_DEF_SLT_LSB
`define ALU_INFO_DEF_SLTU_LSB   `ALU_INFO_DEF_SLT_MSB+1
`define ALU_INFO_DEF_SLTU_MSB   `ALU_INFO_DEF_SLTU_LSB+1-1
`define ALU_INFO_DEF_SLTU       `ALU_INFO_DEF_SLTU_MSB:`ALU_INFO_DEF_SLTU_LSB
`define ALU_INFO_DEF_XOR_LSB    `ALU_INFO_DEF_SLTU_MSB+1
`define ALU_INFO_DEF_XOR_MSB    `ALU_INFO_DEF_XOR_LSB+1-1
`define ALU_INFO_DEF_XOR        `ALU_INFO_DEF_XOR_MSB:`ALU_INFO_DEF_XOR_LSB
`define ALU_INFO_DEF_SRL_LSB    `ALU_INFO_DEF_XOR_MSB+1
`define ALU_INFO_DEF_SRL_MSB    `ALU_INFO_DEF_SRL_LSB+1-1
`define ALU_INFO_DEF_SRL        `ALU_INFO_DEF_SRL_MSB:`ALU_INFO_DEF_SRL_LSB
`define ALU_INFO_DEF_SRA_LSB    `ALU_INFO_DEF_SRL_MSB+1
`define ALU_INFO_DEF_SRA_MSB    `ALU_INFO_DEF_SRA_LSB+1-1
`define ALU_INFO_DEF_SRA        `ALU_INFO_DEF_SRA_MSB:`ALU_INFO_DEF_SRA_LSB
`define ALU_INFO_DEF_OR_LSB     `ALU_INFO_DEF_SRA_MSB+1
`define ALU_INFO_DEF_OR_MSB     `ALU_INFO_DEF_OR_LSB+1-1
`define ALU_INFO_DEF_OR         `ALU_INFO_DEF_OR_MSB:`ALU_INFO_DEF_OR_LSB
`define ALU_INFO_DEF_AND_LSB    `ALU_INFO_DEF_OR_MSB+1
`define ALU_INFO_DEF_AND_MSB    `ALU_INFO_DEF_AND_LSB+1-1
`define ALU_INFO_DEF_AND        `ALU_INFO_DEF_AND_MSB:`ALU_INFO_DEF_AND_LSB
`define ALU_INFO_DEF_LUI_LSB    `ALU_INFO_DEF_AND_MSB+1
`define ALU_INFO_DEF_LUI_MSB    `ALU_INFO_DEF_LUI_LSB+1-1
`define ALU_INFO_DEF_LUI        `ALU_INFO_DEF_LUI_MSB:`ALU_INFO_DEF_LUI_LSB

`define ALU_INFO_WIDTH  `ALU_INFO_DEF_LUI_MSB+1

